name       : okteta
version    : 17.12.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.0/src/okteta-17.12.0.tar.xz : f3cc09032294df15ecad8b01cfd29c468e8f1e98a3b8a1598cc480b826aad07f
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : editor
summary    : KDE hexeditor
description: |
    The program Okteta is an implementation of a standalone, plain old-fashioned hex editor. It is based on the Kasten framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kbookmarks-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kparts-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
