name       : okteta
version    : 0.25.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/okteta/0.25.0/src/okteta-0.25.0.tar.xz : 5e0399195fc2177fc39caf5c24585c9521f38b92c0780f92c329ee737e5e644d
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : editor
summary    : KDE hexeditor
description: |
    The program Okteta is an implementation of a standalone, plain old-fashioned hex editor. It is based on the Kasten framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kbookmarks-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kparts-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
