name       : okteta
version    : 0.26.9
release    : 23
source     :
    - https://cdn.download.kde.org/stable/okteta/0.26.9/src/okteta-0.26.9.tar.xz : 16854c4d4e94838219ae3115a42ba385fda5c87dc6c9865ac90d3774f8d05ffb
homepage   : https://apps.kde.org/okteta/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : editor
summary    : KDE hex editor
description: |
    The program Okteta is an implementation of a standalone, plain old-fashioned hex editor. It is based on the Kasten framework.
builddeps  :
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Qml)
    - pkgconfig(qca2-qt5)
    - pkgconfig(shared-mime-info)
    - kcmutils-devel
    - kcodecs-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - knewstuff-devel
    - kparts-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    # remove HTML docs
    rm -rf $installdir/usr/share/doc
