name       : okteta
version    : 17.04.3
release    : 5
source     :
    - https://download.kde.org/stable/applications/17.04.3/src/okteta-17.04.3.tar.xz : 3bc3ca27026d1a8016621ed5dd754cb5935d192e1f221e732e48b102c5cda907
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : editor
summary    : KDE hexeditor
description: |
    The program Okteta is an implementation of a standalone, plain old-fashioned hex editor. It is based on the Kasten framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kbookmarks-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kparts-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
