name       : okteta
version    : 0.25.4
release    : 15
source     :
    - https://cdn.download.kde.org/stable/okteta/0.25.4/src/okteta-0.25.4.tar.xz : ae2a72d0162184278d1c0e0a73b52751a0181deede0231a4c9d568bb7ac82a52
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : editor
summary    : KDE hex editor
description: |
    The program Okteta is an implementation of a standalone, plain old-fashioned hex editor. It is based on the Kasten framework.
builddeps  :
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kbookmarks-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kparts-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - shared-mime-info
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
