name       : okteta
version    : 17.08.1
release    : 6
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/okteta-17.08.1.tar.xz : 022f6e58f8e82c2ea101c5fbb15f2735c04a3fa7142c55695829c1c3e59f9503
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : editor
summary    : KDE hexeditor
description: |
    The program Okteta is an implementation of a standalone, plain old-fashioned hex editor. It is based on the Kasten framework.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Script)
    - extra-cmake-modules
    - kbookmarks-devel
    - kcmutils-devel
    - kcodecs-devel
    - kcompletion-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdoctools-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - kparts-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
    - shared-mime-info
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
